server:
  port: 9201

spring:
  application:
    name: ruoyi-system
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: ${spring.profiles.active:dev}
      config:
        server-addr: 127.0.0.1:8848
        namespace: ${spring.profiles.active:dev}
        file-extension: yml
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jn_fan_erp?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 10s
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.ruoyi.system.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.ruoyi: debug
    com.jn.erp: debug
